data_transformation:
  top_features: 20

model_trainer:
  test_size: 0.2
  random_state: 42
  
  models:
    logistic_regression:
      module: sklearn.linear_model
      class: LogisticRegression
      params: {}

    knn:
      module: sklearn.neighbors
      class: KNeighborsClassifier
      params: {}

    decision_tree:
      module: sklearn.tree
      class: DecisionTreeClassifier
      params: {}
        

    random_forest:
      module: sklearn.ensemble
      class: RandomForestClassifier
      params: {}
        

    svm:
      module: sklearn.svm
      class: SVC
      params: {}
        

    naive_bayes:
      module: sklearn.naive_bayes
      class: GaussianNB
      params: {}

    xgboost:
      module: xgboost
      class: XGBClassifier
      params:
        use_label_encoder: false
        eval_metric: logloss
       

    catboost:
      module: catboost
      class: CatBoostClassifier
      params: {}

    lightgbm:
      module: lightgbm
      class: LGBMClassifier
      params: {}
       
